apiVersion: v2
name: authservice
description: A Helm chart for Auth Service
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - auth
  - authentication
  - jwt
maintainers:
  - name: Auth Service Team

